version: '3'
services:
  proxysql:
    image: proxysql/proxysql:2.6.3
    ports:
      - "6032:6032"
      - "6070:6070"
      - "6080:6080"

  database-1:
    image: mariadb:11.4.2
    env_file:
      - database.env
    ports:
      - "3307:3306"
    depends_on:
      - proxysql

  database-2:
    image: mariadb:11.4.2
    env_file:
      - database.env
    ports:
      - "3308:3306"
    depends_on:
      - proxysql
      - database-1

  db-loadbalancer:
    image: mariadb/maxscale:24.02.1
    ports:
      - "3306:3306"
      - "8989:8989"
    depends_on:
      - database-1
      - database-2

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev
