version: '3'
services:

  database-1:
    image: mariadb:11.4.2
    env_file:
      - database.env
    ports:
      - "3307:3306"
    volumes:
      - database-1-data:/var/lib/mysql
      - database-1-galera.cnf:/etc/mysql/conf.d

  database-2:
    image: mariadb:11.4.2
    env_file:
      - database.env
    ports:
      - "3308:3306"
    depends_on:
      - database-1
    volumes:
      - database-2-data:/var/lib/mysql
      - database-2-galera.cnf:/etc/mysql/conf.d

  db-loadbalancer:
    image: mariadb/maxscale:24.02.1
    ports:
      - "3306:3306"
      - "8989:8989"
    depends_on:
      - database-1
      - database-2

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev

  python-app:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - keycloak
      - db-loadbalancer

  react-app:
    build: ./frontend/vct_project
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
      - python-app

volumes: # named volumes can be managed easier using docker-compose
  database-1-data:
  database-1-galera.cnf:
  database-2-data:
  database-2-galera.cnf: